version: '3.8'

services:
  nodejs:
    build: .
    command: yarn start:dev
    env_file: ./.env
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app
    networks:
      - nestjs-api
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    container_name: mysqldb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_DOCKER_PORT
    networks:
      - nestjs-api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file: ./.env
    environment:
      PMA_HOST: $MYSQLDB_HOST
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    restart: always
    networks:
      - nestjs-api
networks:
  nestjs-api:
    driver: bridge
